version: "3"
services:
  yee-voice-recognition-server:
    container_name: yee-voice-recognition-server
    build: .
    image: yee-voice
    volumes:
      - ./:/var/www/localhost
    environment:
      - LOG_LEVEL=INFO
    devices:
      - "/dev/snd:/dev/snd"
  yee-voice-recognition-server-dev:
    container_name: yee-voice-recognition-server-dev
    build: .
    image: yee-voice
    volumes:
      - ./:/var/www/localhost
    environment:
      - LOG_LEVEL=DEBUG
    devices:
      - "/dev/snd:/dev/snd"
    command:
      "npm run run-dev"
