version: "3"
services:
  yee-voice-recognition-server:
    container_name: yee-voice-recognition-server
    build: .
    image: yee-voice
    volumes:
      - ./:/var/www/localhost
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - LOG_LEVEL=INFO
      - DISPLAY=unix:$DISPLAY
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - "/dev/snd:/dev/snd"
  yee-voice-recognition-server-dev:
    container_name: yee-voice-recognition-server-dev
    build: .
    image: yee-voice
    volumes:
      - ./:/var/www/localhost
    environment:
      - LOG_LEVEL=DEBUG
    devices:
      - "/dev/snd:/dev/snd"
    command:
      "npm run run-dev"
